version: '2'
services:
  front:
    build: front
    ports: 
      - "8080:8080"
    network_mode: "host"
  back:
    build: back
  keycloak:
    image: "jboss/keycloak"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/test-realm.json
    ports:
      - "8081:8080"
      - "9990:9990"
    volumes:
      - "./keycloak/test-realm.json:/tmp/test-realm.json"


#networks:
#    default:
#        external:
#          name: "host"
